In [1]:
import numpy as np

In [2]:
x = [1,2,3.5,4.8]

In [3]:
type(x)

list

In [4]:
2*x

[1, 2, 3.5, 4.8, 1, 2, 3.5, 4.8]

In [5]:
a = np.array(x)
print(a)

[1.  2.  3.5 4.8]


In [6]:
type(a)

numpy.ndarray

In [7]:
print(a*2)

[2.  4.  7.  9.6]


In [8]:
a.dtype

dtype('float64')

In [9]:
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [10]:
print(x[0])
print(x[0])
print(x[0:3])

1
1
[1 3 5]


In [11]:
x = np.arange(3.2)
y = np.arange(0.1,1.2,0.1)
print(x)
print(y)


[0. 1. 2. 3.]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]


In [12]:
v1 = np.arange(5)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,5)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-10,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)

Creating a numpy array via arange (stop=5) : [0 1 2 3 4]

Creating a numpy array via arange (start=2,stop=5) : [2 3 4]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6 -8]



In [13]:
[[1,1],[2,2], [3,3]]

[[1, 1], [2, 2], [3, 3]]

In [27]:
b = np.array([[1,1],[2,2], [3,3]])

print(b.ndim,b.size)
print(b)

2 6
[[1 1]
 [2 2]
 [3 3]]


In [28]:
b.shape

(3, 2)

In [29]:
np.shape(b)

(3, 2)

In [30]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b = np.expand_dims(b, axis=[0, -1])
print(b)
b.shape

[[[[1]
   [1]]

  [[2]
   [2]]

  [[3]
   [3]]]]


(1, 3, 2, 1)

In [34]:
b = np.squeeze(b)
print(b)
b.shape

[[1 1]
 [2 2]
 [3 3]]


(3, 2)

In [35]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [36]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a = np.linspace(0, 4, 9)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [38]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.diag([1,2,3,4,-1])

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, -1]])

In [42]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
x = np.array([1, 2, 3])
np.repeat(x, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [44]:
x = np.array([1,1,2])
pdf, ebin = np.histogram(x,2)
cbin = 0.5*(ebin[1:]+ebin[:-1])

In [45]:
pdf,cbin

(array([2, 1]), array([1.25, 1.75]))

In [46]:
mat = np.random.normal(2,2.5,(4,8))
mat.shape

(4, 8)

In [47]:
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))

Overall mean of matrix is 
2.138154259517375



In [48]:
print ('Row mean of matrix is \n%s\n'%np.mean(mat, axis=0))

Row mean of matrix is 
[4.45688467 2.54240637 1.13480376 2.23527547 2.78364193 0.64558098
 0.23250909 3.07413181]



In [49]:
print ('Column mean of matrix is \n%s\n'%np.mean(mat, axis=1))

Column mean of matrix is 
[2.58823182 1.40532623 1.98152535 2.57753364]



In [50]:
print ('Overall varience of matrix is %s\n'%np.var(mat))

Overall varience of matrix is 5.93648964302249



In [51]:
print ('Overall standard deviation of matrix is %s\n'%np.std(mat))

Overall standard deviation of matrix is 2.4364912565044206



In [52]:
print ('Overall sum of matrix is %s\n'%np.sum(mat))

Overall sum of matrix is 68.420936304556



In [53]:
print ('Overall min of matrix is %s\n'%np.min(mat))

Overall min of matrix is -2.805488316525489



In [54]:
print ('Overall max of matrix is %s\n'%np.max(mat))

Overall max of matrix is 6.740179939107122



In [55]:
marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks = %s\n'%marks)
print ('Overall 30 percent quantile of marks is %s\n'%(str(np.percentile(marks,30))))

Marks = [ 30  31  32  40  90  95  97  98  99 100]

Overall 30 percent quantile of marks is 37.599999999999994



In [56]:
len(dir(np))

623

# Combining Data

In [57]:
data1 = np.random.randint(5,15,size=(5,3))

In [58]:
data2 = np.random.randint(5,15,size=(5,3))

In [59]:
np.hstack([data1,data2]).shape

(5, 6)

In [60]:
np.vstack([data1, data2]).shape

(10, 3)

In [61]:
np.concatenate([data1, data2], axis=1).shape

(5, 6)

In [62]:
np.stack([data1, data2], axis=-1).shape

(5, 3, 2)

# Save and load data

In [63]:
x = np.linspace(0,5,100)
y = np.sin(x)

In [64]:
y.shape

(100,)

In [65]:
np.savetxt('x.txt',x)

In [66]:
np.savetxt('data.txt',np.c_[x,y])

In [67]:
x = np.loadtxt('x.txt')
x.shape

(100,)

In [68]:
# !cat x.txt

In [69]:
x = np.random.normal(0,1,(1000,1000))

In [70]:
np.savetxt('x.txt',x)

In [71]:
np.save('xdata',x)

In [72]:
x = np.load('xdata.npy')

In [73]:
x.shape

(1000, 1000)

In [74]:
x = np.random.normal(0,1,(100,100))
y = np.random.normal(0,1,(100,100))
z = np.random.normal(0,1,(100,100))

In [75]:
np.savez('dataset',x=x,y=y,z=z)

In [76]:
data = np.load('dataset.npz')

In [77]:
data.files

['x', 'y', 'z']

In [78]:
x = data['x']
y = data['y']
z = data['z']

# how to read CSV in python (without using any library)

In [80]:
f = open('./files/data.csv','r')

In [81]:
data0 = f.read()

In [82]:
data1 = data0.split('\n')

In [83]:
data2 = [i for i in data1 if len(i)!=0]
data2

['name,age,mark', 'ali,18,20', 'zeinab,20,19.5', 'shahin,25,16']

In [84]:
data2[0]

'name,age,mark'

In [85]:
data2[1].split(',')

['ali', '18', '20']

In [86]:
import pandas as pd

In [87]:
pd.read_csv('./files/data.csv')

name  age  mark
0     ali   18  20.0
1  zeinab   20  19.5
2  shahin   25  16.0